### ISSUE TITLE
DirectoryFileInfo.PhysicalPath is always null

### ISSUE THREAD

**Issue by RPaetau** [dazinator/Dazinator.AspNet.Extensions.FileProviders#20]
Hello my good sir! 
Thank you very much for creating this code, its really awesome! Made my day when i found it (: 

There is a minor but though.. 

When using your little extension here, i noticed that the physical paths were not as expected. 
I would expect that the physical path would be a concatination of all the parent directory paths and with the name of the folder appended. 

The tooltip does indicate that the physical path should be null if the file does not exist, so i understand why its like this, but it would be really handy for test scenarios if the physical path correlated to the in memory directory structure you've made.

Or maybe im just using the tool wrong? Please enlighten me (: 

Ps. First time creating a github issue, so i appologize if im breaking some conventions and styles (:

**Comment by RPaetau** [comment]
Apologies, just saw that there is a closed issue that describes the same problem

**Comment by RPaetau** [comment]
Reopening since i think i might be able to argue why it should be set. 

In my case im building a file system tree by taking a given root path, and recursively going through all its children and so on. 

This tree has filters so i can tell it to avoid a directory by passing along a path to avoid, but i cant test this functionality since there are no physical paths to compare to.. 

Am i approaching this the wrong way? (: 

Thanks for your time (:

**Comment by RPaetau** [comment]
Since its recursive i also need the path of the subfolders to start the next run of the recursive function

**Comment by dazinator** [comment]
So you have a root path
`C:/FOO/BAR`

You are building a tree from that root path by recursing through its children.
But you wan't to ignore particular directories?

So as you recurse, can't add the current node to the stack
So when you are here: `C:/FOO/BAR/One`

The stack would contain `/One`

Then when you get to here:
 `C:/FOO/BAR/One/Two`

The stack would contain `/One/Two`

Now in order to ignore a directory you only need its subpath not its full path. For example to ignore the directory  `C:/FOO/BAR/One/Three` you would need to ingore the subpath `/One/Three`

When you are recursing, and you are about to add `Three` to the stack, which already contains `/One` that matches `/One/Three/` so you know you can skip recursing this directory.

None of this requires storing the full physical path of the file, only subpaths..

Does that help? Or am I missing something

**Comment by RPaetau** [comment]
I have to try this out to see if it solves my issue, maybe im just going about this in a poor manner.. 

If you are curious here is my CreateDirectoryTree method

`        private FileTreeNode<FileDirectoryInfo> CreateDirectoryTree(string directoryPath, IEnumerable<GetMultipleFileFiltersQuery.Response> ExclusionFilters)
        {
            var directoryNode = new FileTreeNode<FileDirectoryInfo>(new FileDirectoryInfo{Path = directoryPath, Visited = true, Type = FileDirectoryInfo.TypeEnum.Directory});
            foreach (var directory in _fileProvider.GetDirectoryContents(directoryPath).Where(n => n.IsDirectory))
                if (ExclusionFilters.Any(n => n.Path == directory.PhysicalPath && n.Type == FileFilterType.Exclusion))
                    break;
                else
                    directoryNode.Children.AddFirst(CreateDirectoryTree(directory.PhysicalPath, ExclusionFilters));
            foreach (var file in _fileProvider.GetDirectoryContents(directoryPath).Where(n => !n.IsDirectory))
                if (ExclusionFilters.Any(n => n.Path == file.PhysicalPath && n.Type == FileFilterType.Exclusion))
                    break;
                else
                    directoryNode.Children.AddFirst(new FileTreeNode<FileDirectoryInfo>(new FileDirectoryInfo{Path = file.PhysicalPath, Type = FileDirectoryInfo.TypeEnum.File, Visited = true}));
            return directoryNode;
        }`

**Comment by RPaetau** [comment]
While you were typing that, i was implementing it :D And im happy to say that it works! Thank you very much for the assistance, you gave me just the right nudge to help me figure it out (: 
Closing.

**Comment by dazinator** [comment]
Pleased to hear that :-)
