### ISSUE TITLE
If PhysicalPath was set to Provider root + Name it would work more like a physical provider

### ISSUE THREAD

**Issue by RPaetau** [dazinator/Dazinator.AspNet.Extensions.FileProviders#30]
Hello again Dazinator. I know this issue has been discussed several times, but id like to bring it up again, cause it keeps bothering me..

I really want to use this framework for testing my code, but if i do it contaminates my code, because it works differently than the physical provider.

In my code i iterate through a bunch of directories and i create an in memory tree to represent the folder structure, and i use the physical path since its the simplest way to get the path of an item.
If i want to test this code using the framework here i have to change my code so that the path is a combination of provider root and the name from the fileInfo.

To me thats quite problematic.. The behavior of the framework should replicate what the actual fileproviders(physical, composite and the last one i dont remember) does.

Do you agree? I see the problem in setting a virtual path in a property called PhysicalPath, but i think thats just because the interface is poorly designed, it should just have been called Path.

**Comment by dazinator** [comment]
My opinion on this is currently follows:

Look at other file providers - like the EmbeddedFileProvider: 

https://github.com/aspnet/FileSystem/blob/dev/src/FS.Embedded/EmbeddedResourceFileInfo.cs#L65

They don't set a physical path because there is no physical path - the file is held in memory.
PhysicalPath really only makes sense for the Physical File Provider - you can tell that's the rational behind its name being "PhysicalPath" and the fact that the embedded file provider does not set this.

What does this mean?

If you want to work with this `IFIleProvider` / `IFileInfo` abstraction, you accept that "PhysicalPath" breaks the abstraction because its only relevant for some providers and not others - in this case its relevant for `PhysicalFileProvider` but not `EmbeddedFileProvider` or in my case the `InMemoryFileProvider`.

Therefore my advice is not to ever rely on `PhysicalPath`. If you do you are accepting that you are coupled with PhysicalFileProvider. 

One last point, InMemoryFileProvider is meant to be an IFileProvider implementation, not just a PhysicalFileProvider substitute. For example, if your app used a IFileProvider that went to google cloud storage, and you wanted to write some tests, you could substitute it for an InMemoryFileProvider. 

Saying all this if you really want to set a PhysicalPath - could you just derive your own IFileInfo that looks like this but takes the PhysicalPath:

https://github.com/dazinator/Dazinator.AspNet.Extensions.FileProviders/blob/master/src/Dazinator.AspNet.Extensions.FileProviders/FileInfo/StringFileInfo.cs#L9

Then use that in place of `StringFileInfo` etc?

**Comment by RPaetau** [comment]
Thats a really good point! I totally see now (: 
So its just the dotnet core interfaces being funky ^^ 
It just seemed so wierd to me that the functionality was so different, but i see now that you are not the outlier but the Physical provider is the one causing things to get all wierd.. 

Thanks alot for being patient enough to explain in detail, i hope others wondering the same thing will come here and see this (: 

Closing. (:

**Comment by dazinator** [comment]
No problem - it was confusing for me at first too. Unfortunately microsoft won't improve this design now so its easy to fall into the trap of becoming coupled to the physical file provider and physical file paths if your are not very careful. I suspect for most applications that is just fine, but the more extensible and well tested ones that actually want to take more advantage of the abstraction, well they then hit this bit of hot water. Anyway, hope it's not caused you too much hassle. Please continue to raise anything that you think might improve things as I will always consider any suggestions.
