### ISSUE TITLE
Library has transitive dependency on vulnerable System.Text.Encodings.Web package

### ISSUE THREAD

**Issue by Shazwazza** [dazinator/Dazinator.AspNet.Extensions.FileProviders#51]
The Smidge.InMemory project has a reference to Dazinator.Extensions.FileProviders and a colleague recently mentioned that it has a transitive dependency on the [vulnerable version of System.Text.Encodings.Web](https://github.com/dotnet/announcements/issues/178). Here's an image showing the dependency chain:

![image](https://user-images.githubusercontent.com/1742685/122949999-75975b80-d3bf-11eb-9ef2-2cd5ef609eef.png)

I think it should be a simple fix to just include an explicit reference to the 5.0.1 non-vulnerable version but I think this package is also built to cross compile for netframework too so might need that reference in a couple places.

I've update the Smidge.InMemory project to have the explicit reference but just wanted to report this here too.

**Comment by dazinator** [comment]
Thanks for letting me know, will address this at some point!

**Comment by dazinator** [comment]
Thinking on it a little more, dependency versions specified in a nuspec represent a version constraint on compatible versions of the dependency, so in this case this library just stipulates it needs the consumer to have atleast version 5.0.0 as the "minimum compatible version" of the dependency. I don't think I should bump this compatible version for a patch fix that doesn't effect binary compatibility, because consumers are free to keep their package dependencies up to date for their application using the nuget package manager or any other mechanism they see fit and this package doesn't prevent that. I don't think it's intended in nuget ecosystem for a new patch release of package (in this case 5.0.1) to necessitate in all downstream dependents having to bump their dependency version when binary compatibility is unaffected - as that kind of makes compatibility version constraints in a nuspec file almost redundant and increases the maintaining of all package authors in that dependency graph - I'll update my package, then consumers of my package have to update their packages etc etc all because a dependency at the bottom has an update. So based on that principle - I don't think I should actually do anything here as I think it would be wrong in principle based on how nuget works!

**Comment by Shazwazza** [comment]
fair enough

**Comment by dazinator** [comment]
Thanks though. If it becomes a bigger problem for some reason let me know and I'll reconsider.
